### ISSUE TITLE
Cannot find download.js

### ISSUE THREAD

**Issue by candu** [gunar/shellcheck#18]
shellcheck@0.4.0 doesn't include `download.js` in the uploaded tarball, causing the following error on installation:

```
Error: Cannot find module '/home/vagrant/.nvm/versions/node/v10.16.3/lib/node_modules/shellcheck/download.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

To verify this, I did:

```sh
curl https://registry.npmjs.org/shellcheck/-/shellcheck-0.4.0.tgz > shellcheck-0.4.0.tgz
tar xzvf shellcheck-0.4.0.tgz
ls package
# download.js not included in file list
```

**Comment by gunar** [comment]
Thanks for reporting, published as `0.4.1`
