### ISSUE TITLE
Installation fails on `tar` command

### ISSUE THREAD

**Issue by SRachamim** [gunar/shellcheck#26]
Hey,

When I install `shellcheck` it fails when executing `tar`.

My `package.json`:

```json
    "shellcheck": "^1.0.0",
```

The output:

```shell
error /Users/kishu/Development/dev.azure.com/fundguard/fgrepo/client/node_modules/shellcheck: Command failed.
Exit code: 2
Command: ./install.sh
Arguments:
Directory: /Users/kishu/Development/dev.azure.com/fundguard/fgrepo/client/node_modules/shellcheck
Output:
tar (grandchild): xz: Cannot exec: No such file or directory
tar (grandchild): Error is not recoverable: exiting now
tar: Child died with signal 13
tar: Error is not recoverable: exiting now
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at IncomingMessage.ondata (internal/streams/readable.js:719:22)
    at IncomingMessage.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
Emitted 'error' event on Socket instance at:
    at Socket.onerror (internal/streams/readable.js:760:14)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -32,
  code: 'EPIPE',
```

My `tar --version` output:

```shell
tar (GNU tar) 1.34
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
```

**Comment by gunar** [comment]
Thanks for the bug report.

Apparently [you need to install xz-utils](https://superuser.com/a/801189/115588)—I just learned this myself. Is that something you're able to do in your environment? Does that solve your problem?

In the future, it'd be nice to have an installation process that has nodejs dependencies only.

**Comment by SRachamim** [comment]
Do you think it's reasonable to assume that something is in the environment, except for `node`? Is there a way to make the script more portable?

**Comment by gunar** [comment]
That would be ideal. I've created a new issue to track the portability question: https://github.com/gunar/shellcheck/issues/27
