### ISSUE TITLE
Version 2.0.0 drops Node 10 support

### ISSUE THREAD

**Issue by sgress454** [gunar/shellcheck#53]
When running in Node 10, you now get:
```
    process.exit(shellcheck.status ?? 1);
                                    ^
SyntaxError: Unexpected token ?
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
```

Not saying this needs to be fixed, but please consider adding "Drops support for Node 10" to the changelog as a breaking change if you don't plan on continuing to support it. 🙏

**Comment by sgress454** [comment]
I think for `??` you need at least Node v14.

**Comment by carlocorradini** [comment]
Hey @sgress454
In [`package.json`](https://github.com/gunar/shellcheck/blob/main/package.json#L43) there is the engine restriction on `node: >=16.17.0 || >=v18.4.0`
The engine restrictions is due to [`fsPromises.constants`](https://nodejs.org/api/fs.html#fspromisesconstants) that has been added in _Node.js_ `16.17.0` and `18.4.0`

Moreover, from [npm docs](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines):
> Unless the user has set the `engine-strict` config flag, this field is advisory only and will only produce warnings when your package is installed as a dependency

Therefore only a warning message is produced. 

You are right on the changelog. I'll take care of it immediately.

**Comment by carlocorradini** [comment]
@sgress454
If you discover any further issues, please let us know 🥳🤯
Thanks 😎
